name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/OnBoardingBackend || git clone https://github.com/shahatWM/OnBoardingBackend.git
            cd OnBoardingBackend
            git pull origin main
            sudo docker build -t onboarding-backend .
            sudo docker stop $(sudo docker ps -q --filter ancestor=onboarding-backend) || true
            sudo docker run -d -p 8080:8080 onboarding-backend

